// Code generated by go2go; DO NOT EDIT.


//line ./foo/bar.go2:1
package foo

//line ./foo/bar.go2:1
import "fmt"

//line ./foo/bar.go2:1
type Importable୦ int

//line ./foo/bar.go2:1
var _ = fmt.Errorf
